version: '3.7'

services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres-lesson
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      POSTGRES_DB: app
    volumes:
      - ./data:/var/lib/postgresql